'use strict';

// Site sitemap generator.
//
// This registers under the same name ("sitemap") as the generator from the
// hexo-generator-sitemap plugin. Site scripts load after external plugins,
// so this version replaces it. Reasons to keep the sitemap in the site
// source:
//
//   - the plugin only knows posts, source pages, tags and categories, so the
//     two listing hubs generated by site scripts (essays/, writing/) and the
//     taxonomy hub pages (categories/, tags/) were missing from the sitemap;
//   - tag archives with a single post are thin pages (25 of 46 tags here);
//     they are excluded from the sitemap and get noindex from
//     scripts/seo-filters.js;
//   - priorities can differ per section (posts vs hubs vs archives).
//
// Pagination routes and the noindex /categories/notes/ redirect stub (which
// sets `sitemap: false`) stay out automatically.

const MIN_TAG_POSTS = 2;

function isoDate(moment) {
  const date = moment && typeof moment.toDate === 'function' ? moment.toDate() : moment;
  const time = date instanceof Date ? date : new Date(date || Date.now());
  return Number.isNaN(time.getTime()) ? new Date().toISOString().slice(0, 10) : time.toISOString().slice(0, 10);
}

function xmlEscape(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function cleanUrl(url) {
  return String(url || '').replace(/index\.html$/, '');
}

// Absolute URL for a site path such as "tags/周报/index.html".
function urlOf(siteUrl, path) {
  return encodeURI(`${siteUrl}/${cleanUrl(String(path || '').replace(/^\/+/, ''))}`);
}

hexo.extend.generator.register('sitemap', function(locals) {
  const siteUrl = cleanUrl(String(this.config.url || '').replace(/\/+$/, ''));
  const now = new Date().toISOString().slice(0, 10);
  const urls = [];

  const push = (loc, lastmod, changefreq, priority) =>
    urls.push({ loc: xmlEscape(loc), lastmod, changefreq, priority });

  // Posts
  locals.posts.toArray()
    .filter(post => post.sitemap !== false)
    .forEach(post => push(cleanUrl(post.permalink), isoDate(post.updated || post.date), 'monthly', '0.7'));

  // Source pages (homepage, about, topic hubs, weekly hubs, ...)
  locals.pages.toArray()
    .filter(item => item.sitemap !== false)
    .forEach(item => push(
      urlOf(siteUrl, item.path),
      isoDate(item.updated || item.date),
      'weekly',
      item.path === 'index.html' ? '1.0' : '0.6'
    ));

  // Listing hubs produced by site generators (not part of locals.pages)
  [
    ['essays/index.html', '0.8'],
    ['writing/index.html', '0.8'],
    ['categories/index.html', '0.5'],
    ['tags/index.html', '0.5']
  ].forEach(([path, priority]) => push(urlOf(siteUrl, path), now, 'weekly', priority));

  // Category archives
  locals.categories.toArray()
    .filter(category => category.length > 0)
    .forEach(category => push(urlOf(siteUrl, category.path), now, 'weekly', '0.4'));

  // Tag archives, skipping thin single-post tags
  locals.tags.toArray()
    .filter(tag => tag.length >= MIN_TAG_POSTS)
    .forEach(tag => push(urlOf(siteUrl, tag.path), now, 'weekly', '0.3'));

  const body = urls.map(url => [
    '  <url>',
    `    <loc>${url.loc}</loc>`,
    `    <lastmod>${url.lastmod}</lastmod>`,
    `    <changefreq>${url.changefreq}</changefreq>`,
    `    <priority>${url.priority}</priority>`,
    '  </url>'
  ].join('\n')).join('\n');

  return {
    path: 'sitemap.xml',
    data: `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`
  };
});
